document.addEventListener('DOMContentLoaded', () => {
    // DOM Elements
    const setupContainer = document.getElementById('setup-container');
    const jsonInput = document.getElementById('json-input');
    const startExamBtn = document.getElementById('start-exam-btn');
    const setupError = document.getElementById('setup-error');
    const copyPromptBtn = document.getElementById('copy-prompt-btn');
    const promptText = document.getElementById('prompt-text');
    const progressWrapper = document.getElementById('progress-wrapper');
    
    const questionText = document.getElementById('question-text');
    const optionsContainer = document.getElementById('options-container');
    const feedbackContainer = document.getElementById('feedback-container');
    const feedbackIcon = document.getElementById('feedback-icon');
    const feedbackText = document.getElementById('feedback-text');
    const nextBtn = document.getElementById('next-btn');
    const currentQNumEl = document.getElementById('current-q-num');
    const totalQNumEl = document.getElementById('total-q-num');
    const progressBar = document.getElementById('progress-bar');
    const quizContainer = document.getElementById('quiz-container');
    const resultsContainer = document.getElementById('results-container');
    const scorePercentageEl = document.getElementById('score-percentage');
    const correctCountEl = document.getElementById('correct-count');
    const totalQuestionsEl = document.getElementById('total-questions');
    const resultMessageEl = document.getElementById('result-message');
    const restartBtn = document.getElementById('restart-btn');

    // State
    let currentQuestionIndex = 0;
    let correctAnswersCount = 0;
    let questions = [];

    // Initialize
    function init() {
        // Just bind listeners, the quiz will start when the user inputs JSON
    }

    function handleStartExam() {
        const rawJson = jsonInput.value.trim();
        if (!rawJson) {
            showError('Please paste the JSON generated by the LLM.');
            return;
        }

        try {
            // Remove markdown code blocks if the user copied them
            let cleanJson = rawJson;
            if (cleanJson.startsWith('```')) {
                const firstNewline = cleanJson.indexOf('\n');
                const lastBackticks = cleanJson.lastIndexOf('```');
                if (firstNewline !== -1 && lastBackticks !== -1 && lastBackticks > firstNewline) {
                    cleanJson = cleanJson.substring(firstNewline, lastBackticks).trim();
                }
            }

            questions = JSON.parse(cleanJson);
            
            if (!Array.isArray(questions) || questions.length === 0) {
                throw new Error('The JSON must be a valid array with at least one question.');
            }

            // Start quiz
            setupError.classList.add('hidden');
            setupContainer.classList.add('hidden');
            quizContainer.classList.remove('hidden');
            progressWrapper.classList.remove('hidden');

            totalQNumEl.textContent = questions.length;
            totalQuestionsEl.textContent = questions.length;
            loadQuestion();
        } catch (error) {
            showError('Error processing JSON: Verify that the format is correct.');
            console.error(error);
        }
    }

    function showError(msg) {
        setupError.textContent = msg;
        setupError.classList.remove('hidden');
    }

    function loadQuestion() {
        // Reset state for new question
        feedbackContainer.classList.add('hidden');
        nextBtn.classList.add('hidden');
        optionsContainer.innerHTML = '';
        
        const question = questions[currentQuestionIndex];
        
        // Update progress
        currentQNumEl.textContent = currentQuestionIndex + 1;
        const progressPercent = (currentQuestionIndex / questions.length) * 100;
        progressBar.style.width = `${progressPercent}%`;

        // Render question
        questionText.textContent = question.question;

        // Render options
        for (const [letter, text] of Object.entries(question.options)) {
            const optionEl = document.createElement('div');
            optionEl.className = 'option';
            optionEl.dataset.letter = letter;
            
            optionEl.innerHTML = `
                <span class="letter">${letter}.</span>
                <span class="text">${text}</span>
            `;
            
            optionEl.addEventListener('click', () => handleOptionClick(letter, optionEl));
            optionsContainer.appendChild(optionEl);
        }
    }

    function handleOptionClick(selectedLetter, optionElement) {
        // Prevent clicking if already answered
        if (optionsContainer.classList.contains('answered')) return;
        optionsContainer.classList.add('answered');

        const question = questions[currentQuestionIndex];
        const correctLetter = question.answer.trim();
        const isCorrect = selectedLetter === correctLetter;

        // Disable all options
        const allOptions = optionsContainer.querySelectorAll('.option');
        allOptions.forEach(opt => {
            opt.classList.add('disabled');
            if (opt.dataset.letter === correctLetter) {
                opt.classList.add('correct');
            }
        });

        if (isCorrect) {
            optionElement.classList.add('correct');
            correctAnswersCount++;
            showFeedback(true, 'Correct!');
        } else {
            optionElement.classList.add('wrong');
            showFeedback(false, `Incorrect. The correct answer is ${correctLetter}.`);
        }

        nextBtn.classList.remove('hidden');
    }

    function showFeedback(isCorrect, message) {
        feedbackContainer.className = `feedback-container ${isCorrect ? 'correct' : 'wrong'}`;
        feedbackIcon.textContent = isCorrect ? '✅' : '❌';
        feedbackText.textContent = message;
        feedbackContainer.classList.remove('hidden');
    }

    function showResults() {
        quizContainer.classList.add('hidden');
        resultsContainer.classList.remove('hidden');
        progressBar.style.width = '100%';

        const percentage = Math.round((correctAnswersCount / questions.length) * 100);
        
        // Animate score circle
        let currentPercent = 0;
        const interval = setInterval(() => {
            currentPercent++;
            scorePercentageEl.textContent = `${currentPercent}%`;
            document.querySelector('.score-circle').style.background = `conic-gradient(var(--accent) ${currentPercent}%, transparent 0%)`;
            
            if (currentPercent >= percentage) {
                clearInterval(interval);
            }
        }, 20);

        if (percentage === 0) {
             scorePercentageEl.textContent = `0%`;
             document.querySelector('.score-circle').style.background = `conic-gradient(var(--accent) 0%, transparent 0%)`;
        }

        correctCountEl.textContent = correctAnswersCount;

        if (percentage >= 70) {
            resultMessageEl.textContent = 'Congratulations! You passed the practice exam.';
            resultMessageEl.style.color = 'var(--success)';
            document.querySelector('.score-circle').style.background = `conic-gradient(var(--success) ${percentage}%, transparent 0%)`;
        } else {
            resultMessageEl.textContent = 'You did not reach the minimum score. Keep practicing!';
            resultMessageEl.style.color = 'var(--error)';
            document.querySelector('.score-circle').style.background = `conic-gradient(var(--error) ${percentage}%, transparent 0%)`;
        }
    }

    // Event Listeners
    startExamBtn.addEventListener('click', handleStartExam);
    
    copyPromptBtn.addEventListener('click', () => {
        navigator.clipboard.writeText(promptText.textContent)
            .then(() => {
                copyPromptBtn.textContent = 'Copied!';
                setTimeout(() => {
                    copyPromptBtn.textContent = 'Copy';
                }, 2000);
            });
    });

    nextBtn.addEventListener('click', () => {
        currentQuestionIndex++;
        optionsContainer.classList.remove('answered');
        
        if (currentQuestionIndex < questions.length) {
            loadQuestion();
        } else {
            showResults();
        }
    });

    restartBtn.addEventListener('click', () => {
        currentQuestionIndex = 0;
        correctAnswersCount = 0;
        resultsContainer.classList.add('hidden');
        progressWrapper.classList.add('hidden');
        setupContainer.classList.remove('hidden');
        jsonInput.value = '';
    });

    // Start
    init();
});
