import '../style.css';

interface Question {
  id?: number;
  question: string;
  options: Record<string, string>;
  answer: string;
  explanation?: string;
  // Populated at runtime the first time the question is rendered.
  shuffledOptions?: ShuffledOption[];
  correctLetter?: string;
}

interface ShuffledOption {
  letter: string;
  text: string;
  isCorrect: boolean;
}

/** Get an element by id, asserting it exists (fails loud during development). */
function byId<T extends HTMLElement>(id: string): T {
  const el = document.getElementById(id);
  if (!el) {
    throw new Error(`Missing element #${id}`);
  }
  return el as T;
}

document.addEventListener('DOMContentLoaded', () => {
  // DOM Elements
  const setupContainer = byId('setup-container');
  const jsonInput = byId<HTMLTextAreaElement>('json-input');
  const startExamBtn = byId('start-exam-btn');
  const setupError = byId('setup-error');
  const copyPromptBtn = byId('copy-prompt-btn');
  const promptText = byId('prompt-text');
  const progressWrapper = byId('progress-wrapper');

  const questionText = byId('question-text');
  const optionsContainer = byId('options-container');
  const feedbackContainer = byId('feedback-container');
  const feedbackIcon = byId('feedback-icon');
  const feedbackText = byId('feedback-text');
  const feedbackExplanation = byId('feedback-explanation');
  const nextBtn = byId('next-btn');
  const currentQNumEl = byId('current-q-num');
  const totalQNumEl = byId('total-q-num');
  const progressBar = byId('progress-bar');
  const currentScoreEl = byId('current-score');
  const quizContainer = byId('quiz-container');
  const resultsContainer = byId('results-container');
  const scorePercentageEl = byId('score-percentage');
  const correctCountEl = byId('correct-count');
  const totalQuestionsEl = byId('total-questions');
  const resultMessageEl = byId('result-message');
  const restartBtn = byId('restart-btn');
  const scoreCircle = document.querySelector<HTMLElement>('.score-circle');

  // State
  let currentQuestionIndex = 0;
  let correctAnswersCount = 0;
  let questions: Question[] = [];

  function handleStartExam(): void {
    const rawJson = jsonInput.value.trim();
    if (!rawJson) {
      showError('Please paste the JSON generated by the LLM.');
      return;
    }

    try {
      // Remove markdown code blocks if the user copied them
      let cleanJson = rawJson;
      if (cleanJson.startsWith('```')) {
        const firstNewline = cleanJson.indexOf('\n');
        const lastBackticks = cleanJson.lastIndexOf('```');
        if (firstNewline !== -1 && lastBackticks !== -1 && lastBackticks > firstNewline) {
          cleanJson = cleanJson.substring(firstNewline, lastBackticks).trim();
        }
      }

      const parsed: unknown = JSON.parse(cleanJson);

      if (!Array.isArray(parsed) || parsed.length === 0) {
        throw new Error('The JSON must be a valid array with at least one question.');
      }

      questions = parsed as Question[];

      // Start quiz
      setupError.classList.add('hidden');
      setupContainer.classList.add('hidden');
      quizContainer.classList.remove('hidden');
      progressWrapper.classList.remove('hidden');

      totalQNumEl.textContent = String(questions.length);
      totalQuestionsEl.textContent = String(questions.length);
      currentScoreEl.textContent = '0';
      loadQuestion();
    } catch (error) {
      showError('Error processing JSON: Verify that the format is correct.');
      console.error(error);
    }
  }

  function showError(msg: string): void {
    setupError.textContent = msg;
    setupError.classList.remove('hidden');
  }

  function loadQuestion(): void {
    // Reset state for new question
    feedbackContainer.classList.add('hidden');
    nextBtn.classList.add('hidden');
    optionsContainer.innerHTML = '';

    const question = questions[currentQuestionIndex];

    // Update progress
    currentQNumEl.textContent = String(currentQuestionIndex + 1);
    const progressPercent = (currentQuestionIndex / questions.length) * 100;
    progressBar.style.width = `${progressPercent}%`;

    // Render question
    questionText.textContent = question.question;

    // Shuffle options once per question so the correct answer isn't always
    // in the same position (LLMs tend to place it at B).
    if (!question.shuffledOptions) {
      const entries = Object.entries(question.options);
      // Fisher-Yates shuffle
      for (let i = entries.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [entries[i], entries[j]] = [entries[j], entries[i]];
      }
      const labels = ['A', 'B', 'C', 'D', 'E', 'F', 'G'];
      const originalCorrect = String(question.answer).trim();
      question.shuffledOptions = entries.map(([origLetter, text], idx) => ({
        letter: labels[idx],
        text,
        isCorrect: origLetter === originalCorrect,
      }));
      const correct = question.shuffledOptions.find((o) => o.isCorrect);
      question.correctLetter = correct ? correct.letter : originalCorrect;
    }

    // Render options
    for (const opt of question.shuffledOptions) {
      const optionEl = document.createElement('div');
      optionEl.className = 'option';
      optionEl.dataset.letter = opt.letter;

      optionEl.innerHTML = `
        <span class="letter">${opt.letter}.</span>
        <span class="text">${opt.text}</span>
      `;

      optionEl.addEventListener('click', () => handleOptionClick(opt.letter, optionEl));
      optionsContainer.appendChild(optionEl);
    }
  }

  function handleOptionClick(selectedLetter: string, optionElement: HTMLElement): void {
    // Prevent clicking if already answered
    if (optionsContainer.classList.contains('answered')) return;
    optionsContainer.classList.add('answered');

    const question = questions[currentQuestionIndex];
    const correctLetter = question.correctLetter;
    const isCorrect = selectedLetter === correctLetter;

    // Disable all options
    const allOptions = optionsContainer.querySelectorAll<HTMLElement>('.option');
    allOptions.forEach((opt) => {
      opt.classList.add('disabled');
      if (opt.dataset.letter === correctLetter) {
        opt.classList.add('correct');
      }
    });

    if (isCorrect) {
      optionElement.classList.add('correct');
      correctAnswersCount++;
      showFeedback(true, 'Correct!', question.explanation);
    } else {
      optionElement.classList.add('wrong');
      showFeedback(false, `Incorrect. The correct answer is ${correctLetter}.`, question.explanation);
    }

    const answeredQuestions = currentQuestionIndex + 1;
    const currentScore = Math.round((correctAnswersCount / answeredQuestions) * 100);
    currentScoreEl.textContent = String(currentScore);

    nextBtn.classList.remove('hidden');
  }

  function showFeedback(isCorrect: boolean, message: string, explanation?: string): void {
    feedbackContainer.className = `feedback-container ${isCorrect ? 'correct' : 'wrong'}`;
    feedbackIcon.textContent = isCorrect ? '✅' : '❌';
    feedbackText.textContent = message;

    if (explanation && explanation.trim()) {
      feedbackExplanation.textContent = explanation.trim();
      feedbackExplanation.classList.remove('hidden');
    } else {
      feedbackExplanation.textContent = '';
      feedbackExplanation.classList.add('hidden');
    }

    feedbackContainer.classList.remove('hidden');
  }

  function showResults(): void {
    quizContainer.classList.add('hidden');
    resultsContainer.classList.remove('hidden');
    progressBar.style.width = '100%';

    const percentage = Math.round((correctAnswersCount / questions.length) * 100);

    // Animate score circle
    let currentPercent = 0;
    const interval = setInterval(() => {
      currentPercent++;
      scorePercentageEl.textContent = `${currentPercent}%`;
      if (scoreCircle) {
        scoreCircle.style.background = `conic-gradient(var(--accent) ${currentPercent}%, transparent 0%)`;
      }

      if (currentPercent >= percentage) {
        clearInterval(interval);
      }
    }, 20);

    if (percentage === 0) {
      scorePercentageEl.textContent = `0%`;
      if (scoreCircle) {
        scoreCircle.style.background = `conic-gradient(var(--accent) 0%, transparent 0%)`;
      }
    }

    correctCountEl.textContent = String(correctAnswersCount);

    if (percentage >= 70) {
      resultMessageEl.textContent = 'Congratulations! You passed the practice exam.';
      resultMessageEl.style.color = 'var(--success)';
      if (scoreCircle) {
        scoreCircle.style.background = `conic-gradient(var(--success) ${percentage}%, transparent 0%)`;
      }
    } else {
      resultMessageEl.textContent = 'You did not reach the minimum score. Keep practicing!';
      resultMessageEl.style.color = 'var(--error)';
      if (scoreCircle) {
        scoreCircle.style.background = `conic-gradient(var(--error) ${percentage}%, transparent 0%)`;
      }
    }
  }

  // Event Listeners
  startExamBtn.addEventListener('click', handleStartExam);

  copyPromptBtn.addEventListener('click', () => {
    navigator.clipboard.writeText(promptText.textContent ?? '').then(() => {
      copyPromptBtn.textContent = 'Copied!';
      setTimeout(() => {
        copyPromptBtn.textContent = 'Copy';
      }, 2000);
    });
  });

  nextBtn.addEventListener('click', () => {
    currentQuestionIndex++;
    optionsContainer.classList.remove('answered');

    if (currentQuestionIndex < questions.length) {
      loadQuestion();
    } else {
      showResults();
    }
  });

  restartBtn.addEventListener('click', () => {
    currentQuestionIndex = 0;
    correctAnswersCount = 0;
    currentScoreEl.textContent = '0';
    resultsContainer.classList.add('hidden');
    progressWrapper.classList.add('hidden');
    setupContainer.classList.remove('hidden');
    jsonInput.value = '';
  });
});
